describe("Reports", () => {
  beforeEach(() => {
    cy.visit("/");
    cy.get("#cy__loginEmail").type("naveed@maxenius.agency");
    cy.get("#cy__loginPass").type("Maxenius123");
    cy.get("#cy__loginbtn").click();
  });
  it("Overview Report", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get("#cy_DateRange").click();
    cy.contains('ul[role="listbox"] li', "Today").click();
    cy.get("#cy__GenerateOverviewBtn").click();
    cy.wait(5000).get("#cy_DateRange").click();
    cy.contains('ul[role="listbox"] li', "Month to Date").click();
    cy.get("#cy__GenerateOverviewBtn").click();
    cy.wait(5000).get("#cy_DateRange").click();
    cy.contains('ul[role="listbox"] li', "Year to Date").click();
    cy.get("#cy__GenerateOverviewBtn").click();
    cy.wait(5000).get("#cy_DateRange").click();
    cy.contains('ul[role="listbox"] li', "Chose Date Range").click();
    cy.get("#cy__SelectDateRange").clear().type("06/01/2024 06/30/2024");
    cy.get("body").click(0, 0);
    cy.get("#cy__GenerateOverviewBtn").click();
  });
  it("Revenue Report ", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get("#cy__RevenueReport").click();
    cy.contains('ul[role="listbox"] li', "Refine Staging").click();
    cy.wait(5000);
    cy.get("#cy__RevenueReport").click().click();
    cy.contains('ul[role="listbox"] li', "my website").click();
    cy.get("#cy__PaymentMethod").click();
    cy.contains('ul[role="listbox"] li', "COD").click();
    cy.wait(3000);
    cy.get("#cy__PaymentMethod").click().click();
    cy.contains('ul[role="listbox"] li', "INVOICE").click();
    cy.get("#RevenueDateSelection").click();
    cy.contains('ul[role="listbox"] li', "All Time").click();
    cy.get("#GenerateRevenueBtn").click();
  });
  it("Product Stock Status ", () => {
    cy.contains("Reports").should("be.visible").click();
    const previousDate = "06/01/2024";
    cy.get("#cy__ProductStockStatus").click();
    cy.get("#cy__ProductStockStatus").clear().type(previousDate);
    cy.get("body").click(0, 0);
    cy.get("#cy__ProductStockStatus").should("have.value", previousDate);
    cy.get("#cy__GetStockStatus").click();
  });
  it("Product Report All Time", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get('[title="Products"]').click();
    cy.get("#cy__ProductDateRange").click();
    cy.contains('ul[role="listbox"] li', "All Time").click();
    cy.get("#cy__GenerateProductReport").click();
    cy.wait(5000).get("#cy__ProductDateRange").click();
    cy.contains('ul[role="listbox"] li', "Today").click();
    cy.get("#cy__GenerateProductReport").click();
    cy.wait(5000).get("#cy__ProductDateRange").click();
    cy.contains('ul[role="listbox"] li', "Week to Date").click();
    cy.get("#cy__GenerateProductReport").click();
    cy.wait(5000).get("#cy__ProductDateRange").click();
    cy.contains('ul[role="listbox"] li', "Month to Date").click();
    cy.get("#cy__GenerateProductReport").click();
    cy.wait(5000).get("#cy__ProductDateRange").click();
    cy.contains('ul[role="listbox"] li', "Year to Date").click();
    cy.get("#cy__GenerateProductReport").click();
    cy.wait(5000).get("#cy__ProductDateRange").click();
    cy.contains('ul[role="listbox"] li', "Chose Date Range").click();
    cy.get("#cy__FromTo").clear().type("06/01/2024 06/30/2024");
    cy.get("body").click(0, 0);
    cy.get("#cy__GenerateProductReport").click();
  });
  it("Expiry Report ", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get('[title="Products"]').click();
    cy.get("#ProductExpiryReport").click();
  });
  it("Product Sale", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get('[title="Products"]').click();
    cy.get("#cy__SearchProduct").type("Surbex z");
    cy.contains('ul[role="listbox"] li', "Surbex z").click();
    cy.get("body").click(0, 0);
    cy.get("#cy__GenerateProductSaleReport").click();
  });
  it("Customers", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get('[title="Customers"]').click();
    cy.get("#cy__CustomerDateRange").click();
    cy.contains('ul[role="listbox"] li', "All Time").click();
    cy.get("#cy__GenerateCustomerSpentReport").click();
    cy.wait(5000).get("#cy__CustomerDateRange").click();
    cy.contains('ul[role="listbox"] li', "Today").click();
    cy.get("#cy__GenerateCustomerSpentReport").click();
    cy.wait(5000).get("#cy__CustomerDateRange").click();
    cy.contains('ul[role="listbox"] li', "Week to Date").click();
    cy.get("#cy__GenerateCustomerSpentReport").click();
    cy.wait(5000).get("#cy__CustomerDateRange").click();
    cy.contains('ul[role="listbox"] li', "Year to Date").click();
    cy.get("#cy__GenerateCustomerSpentReport").click();
    cy.wait(5000).get("#cy__CustomerDateRange").click();
    cy.contains('ul[role="listbox"] li', "Chose Date Range").click();
    cy.get("#cy__CustomerFromTo").clear().type("06/01/2024 06/30/2024");
    cy.get("body").click(0, 0);
    cy.get("#cy__GenerateCustomerSpentReport").click();
  });
  it("Batch Detail ", () => {
    cy.contains("Reports").should("be.visible").click();
    cy.get('[title="Batch Details"]').click();
    cy.get("#cy__SelectBatch").type("BATCH-1719328192828-669");
    cy.contains('ul[role="listbox"] li', "BATCH-1719328192828-669").click();
    cy.get("#cy__BatchDateRange").click();
    cy.contains('ul[role="listbox"] li', "Chose Date Range").click();
    cy.get("#cy__BatchFromto").click();
    cy.get("#cy__BatchFromto").clear().type("06/01/2024 06/30/2024");
    cy.get("body").click(0, 0);
    cy.get("#cy__GenerateBatchReport").click();
  });
});
