export const customerDataLabels = {
  name: 'Name des Projekts',
  company: 'Firma des Kunden',
  firstName: 'Vorname',
  lastName: 'Nachname',
  address1: 'Straße',
  address2: 'Stock, Stiege, Tür',
  country: 'Land',
  zipCode: 'PLZ',
  email: 'E-mail',
  phone: 'Tel. Nr.',
};

export const assemblerDataLabels = {
  company: 'Firma des Verarbeiters',
  firstName: 'Vorname',
  lastName: 'Nachname',
  address1: 'Straße',
  address2: 'Stock, Stiege, Tür',
  country: 'Land',
  zipCode: 'PLZ',
  email: 'E-mail',
  phone: 'Tel. Nr.',
};

export const profileDataLabels = {
  profile: 'Profil',
  coating: 'Beschichtung',
  specialColor: 'Spezialbeschichtung',
  wallWidth: 'Mauerbreite',
  externalOffset: 'Überstand außen (mm)',
  internalOffset: 'Überstand innen (mm, Dachseite)',
  aDimension: 'A-Maß (mm)',
  cDimension: 'C-Maß (mm)',
  pitch: 'Standard Gefälle (°)',
  materialThickness: 'Blechstärke',
  holder: 'Standard Halterabstand (mm)',
  endCapTailLength: 'Standard Länge Endkappe (mm)',
};

export const toastMessages = {
  error: {
    common: 'Ein unbekannter Fehler ist aufgetreten',
    noPDF: 'In diesem Projekt wurde kein PDF gefunden',
    notFound: 'Projekt nicht gefunden',
  },
  success: {
    duplicated: 'Projekt dupliziert',
    locked: 'Projekt erfolgreich gesperrt',
    unLocked: 'Projekt erfolgreich freigeschaltet',
    deleted: 'Projekt erfolgreich gelöscht',
  },
};

export const miscDataLabels = { note: 'Note' };

export const editor = {
  dailogs: {
    discard: {
      text: 'Wenn Sie dieses Projekt nochmal bearbeiten möchten gehen alle aktuellen Änderungen im jetzigen Zustand verloren.',
      buttons: {
        duplicate: 'Duplizieren',
        confirm: 'Bestätigen',
        cancel: 'Abbrechen',
      },
    },
    chooseProfile: {
      text: 'Standardmaß Profillängen',
    },
  },
  pdf: {
    buttons: {
      save: 'Speichern',
      updateCanvas: 'Zeichnung mit PDF Eingaben updaten',
      exportPDF: 'PDF exportieren',
      exportCSV: 'CSV exportieren',
      confirm: 'Bestätigen',
      sentenceOutside: 'Satz draußen',
      sentenceInside: 'Sentence inside',
      split: 'Aufteilen',
    },
    form: {
      header: {
        material: 'Werkstoff',
        strength: 'Stärke',
        corrosionProtection: 'Korrosionsschutz',
        buildingHeight: 'Geb.höhe',
        clearanceTolerances: 'Freimaßtoleranzen gemäß DIN EN ISO 2768',
        sheetMetalBaseMaterial: 'Grundwerkstoff Blech: EN AW-5005',
        baseMaterialHolder: 'Grundwerkstoff Holter: EN AW-6060',
        productText:
          'Unsere metallischen Produkte zu Bauzwecken werden in der EXC2 gemäß der DIN EN 1090-2 bzw. DIN EN 1090-3 hergestellt',
        change: 'Anderung',
        date: 'Datum',
        name: 'Name',
        scale: 'Maßstab',
        articleNo: 'Artikelnr',
        auNo: 'AU-Nr',
        customer: 'Kunde',
        com: 'Kom.',
        sheet: 'Blatt',
      },
      profile: {
        material: 'Werkstoff',
        aluminum: 'Alu',
        steel: 'Stahl',
        strength: 'Stärke',
        va: 'VA',
        materialThickness: 'Materialstärke',
        corrosionProtection: 'Korrosionsschutz',
        buildingHeight: 'Gebäudehöhe',
        plastering: 'Verputzen',
        no: 'nein',
        type: 'Typ',
        piece: 'Stück',
        damagedByIt: 'davon besch',
        holder: 'Halter',
        without: 'OHNE',
        w: 'w',
        patent: 'Patent',
        stable: 'Stabil',
        additionalVerb: 'zus. Verb.',
        smoothSheetMetal: 'Glattblech',
        fineRidges: 'Feinriffel',
        ws: 'WS',
        ae_ha: 'AE-Ha',
        ie_ha: 'IE-Ha',
        yes: 'JA',
        gef_u: 'Gef.U.',
        art: 'Kunstst',
        gt: 'GT',
        yellow: 'gelb',
        gotOver: 'Überstand',
        holderDepreciation: 'Halterab',
        akLoose: 'AK lose',
        plaster: 'Putz',
        clinker: 'Klinker',
        gradient: 'Gefälle',
        packSeparately: 'GETRENNT PACKEN',
        separately: 'GETRENNT',
        area: 'BEREICH',
        pos: 'POS',
        until: 'bis',
        devi: 'Abw.',
        runningMeter: 'lfm.',
        ie: 'IE',
        ge: 'GE',
        te: 'TE',
        ak: 'AK',
        ek: 'EK',
        ae: 'AE',
        eku: 'EKÜ',
        au: 'AU',
        sb: 'SB',
        l: 'L',
        s: 'S',
        t: 'T',
        overhang: 'Überhang',
        angle: 'Winkel',
        schere: 'Schere',
        trumpF: 'Trumpf',
        hull: 'Rumpf',
        ref: 'Bez',
        lMabe: 'L-Maße',
        finalLeft: 'Abschl-li',
        finalRight: 'Abschl-re',
        cutS: 'Zuschnitt S.',
        cutting: 'Zuschnitt',
        friemsnGemban: 'Friemsn gemban',
        partsList: 'Stückliste',
        packTogetherWithAU: 'Zusammen packen mit AU',
        offsetSt: 'Versatzst',
        specialMoldedParts: 'Sonderformteile',
        coatedWithIt: 'Davon beschichtet',
        holderDistance: 'Halterabst',
        verp: 'verp',
        posNoGrave: 'Pos.Nr.grave',
        whatFilzst: '...mit Filzst',
        plasterWeldSeams: 'Schweißnähte verputzen',
        dimensions: 'Maße',
        dimension: 'Maß',
        forArea: 'für Bereich',
        remarks: 'Bemerkungen',
        antiDrumming: 'Antidröhn',
        molding: 'Formteil',
        marketing: 'Markierung der Pos.-Nr. mittels',
        permanentMarker: 'Permanentmarker für NATUR',
      },
      footer: {
        FreimaBtoleranaenAccordingTo: 'FreimaBtoleranaen gemaB',
        baseMaterialHolder: 'Grundwerkstoff Halter:EN AW-6060',
        addendumToAU: 'Nachtrag zu AU.',
        addendum: 'Nachtrag',
        contact: {
          pohlDWSGmbH: 'Pohl DWS GmbH',
          nickePutz: 'Nickepütz 33',
          werkDuren: 'Werk düren',
          duren: 'düren',
          tel: '0 24 21 / 96 58-0',
          fax: '0 24 21 / 96 58 90',
          tel2: '+49 2421 9658-0',
          fax2: '+49 2421 9658-90',
          code: 'D-52349',
          germany: 'Deutschland',
          mail: 'info@haushaut.com',
          site: 'www.haushaut.com',
          managingDirector: 'Geschäftsführer',
          bankDetails: 'Bankverbindung',
        },
      },
      sidebar: {
        selectProfile: 'Wähle Profil',
      },
    },
  },
};
export const auth = {
  sign_in: {
    button_label: 'anmelden',
    email_input_placeholder: 'Deine Email Adresse',
    password_input_placeholder: 'Deine Passwort',
    password_label: 'Deine Passwort',
    email_label: 'Deine Email Adresse',
    loading_button_label: 'Einloggen...',
    link_text: 'Sie haben bereits ein Konto? anmelden',
  },
  sign_up: {
    button_label: 'Melden Sie sich an',
    loading_button_label: 'Anmelden...',
    confirmation_text: 'Checken Sie Ihre Email für den Bestätigungslink',
    email_label: 'Email Adresse',
    email_input_placeholder: 'Deine Email Adresse',
    password_label: 'Erstellen Sie ein Passwort',
    password_input_placeholder: 'Deine Passwort',
    link_text: 'Sie haben noch kein Konto? Melden Sie sich an',
  },
  forgotten_password: {
    email_label: 'Email Adresse',
    email_input_placeholder: 'Deine Email Adresse',
    button_label: 'Senden Sie eine Anweisung zum Zurücksetzen des Passworts',
    confirmation_text:
      'Überprüfen Sie Ihre Email auf den Link zum Zurücksetzen des Passworts',
    link_text: 'Haben Sie Ihr Passwort vergessen?',
    loading_button_label: 'Senden von Reset-Anweisungen...',
    password_label: 'Passwort',
  },
  update_password: {
    button_label: 'Aktualisieren',
    confirmation_text: 'Passwort erfolgreich aktualisiert',
    loading_button_label: 'Aktualisierung...',
    password_label: 'Passwort',
    password_input_placeholder: 'Passwort',
  },
};
export const languageData = {
  auth: auth,
  dashboard: {
    name: 'Armaturenbrett',
    header: {
      superUserMessage: 'Nachricht des Tages',
    },
    sidebar: {
      allProjects: 'Alle Projekte',
      openProjects: 'Offene Projekte',
      finishedProjects: 'Abgeschlossene ERP Projekte',
      resetPassword: 'Passwort zurücksetzen',
      logout: 'Ausloggen',
    },
    table: {
      columns: {
        id: 'ID',
        projectName: 'Projektname',
        location: 'Standort',
        status: 'Status',
        sales: 'Außendienst',
        action: 'Auswählen',
      },
      search: {
        label: 'Suche',
        placeholder: 'Name, ID, etc...',
      },
      action: 'Action',
      new: 'Neues Projekt',
    },
  },
  form: {
    steps: ['Kundendaten', 'Verarbeiter', 'Projektdaten', 'Verschiedenes'],
    actions: {
      next: 'Weiter',
      back: 'Zurück',
      create: 'Erstellen',
      cancel: 'Abbrechen',
      reset: 'Zurücksetzen',
    },
    customerData: {
      labels: customerDataLabels,
    },
    assemblerData: {
      labels: assemblerDataLabels,
    },
    profileData: {
      labels: profileDataLabels,
    },
    miscData: {
      labels: miscDataLabels,
    },
  },
  toastMessage: toastMessages,
  editor: editor,
};
